# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtyczka_projekt_2_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wtyczka_QGISDialogBase(object):
    def setupUi(self, wtyczka_QGISDialogBase):
        wtyczka_QGISDialogBase.setObjectName("wtyczka_QGISDialogBase")
        wtyczka_QGISDialogBase.resize(743, 529)
        self.button_box = QtWidgets.QDialogButtonBox(wtyczka_QGISDialogBase)
        self.button_box.setGeometry(QtCore.QRect(510, 480, 211, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.Wybierz_warstwe = QtWidgets.QLabel(wtyczka_QGISDialogBase)
        self.Wybierz_warstwe.setGeometry(QtCore.QRect(140, 40, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Wybierz_warstwe.setFont(font)
        self.Wybierz_warstwe.setObjectName("Wybierz_warstwe")
        self.mMapLayerComboBox = QgsMapLayerComboBox(wtyczka_QGISDialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(410, 60, 231, 27))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.licz_przewyzszenie = QtWidgets.QPushButton(wtyczka_QGISDialogBase)
        self.licz_przewyzszenie.setGeometry(QtCore.QRect(80, 180, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.licz_przewyzszenie.setFont(font)
        self.licz_przewyzszenie.setObjectName("licz_przewyzszenie")
        self.licz_powierzchnie = QtWidgets.QPushButton(wtyczka_QGISDialogBase)
        self.licz_powierzchnie.setGeometry(QtCore.QRect(450, 180, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.licz_powierzchnie.setFont(font)
        self.licz_powierzchnie.setObjectName("licz_powierzchnie")
        self.wynik = QtWidgets.QTextEdit(wtyczka_QGISDialogBase)
        self.wynik.setGeometry(QtCore.QRect(100, 370, 531, 87))
        self.wynik.setObjectName("wynik")
        self.line = QtWidgets.QFrame(wtyczka_QGISDialogBase)
        self.line.setGeometry(QtCore.QRect(0, 130, 741, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(wtyczka_QGISDialogBase)
        self.line_2.setGeometry(QtCore.QRect(360, 140, 20, 181))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(wtyczka_QGISDialogBase)
        self.line_3.setGeometry(QtCore.QRect(0, 310, 741, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.retranslateUi(wtyczka_QGISDialogBase)
        self.button_box.accepted.connect(wtyczka_QGISDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(wtyczka_QGISDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(wtyczka_QGISDialogBase)

    def retranslateUi(self, wtyczka_QGISDialogBase):
        _translate = QtCore.QCoreApplication.translate
        wtyczka_QGISDialogBase.setWindowTitle(_translate("wtyczka_QGISDialogBase", "projekt_2"))
        self.Wybierz_warstwe.setText(_translate("wtyczka_QGISDialogBase", "Wybierz warstwę "))
        self.licz_przewyzszenie.setText(_translate("wtyczka_QGISDialogBase", "Licz przewyższenie [m]"))
        self.licz_powierzchnie.setText(_translate("wtyczka_QGISDialogBase", "Licz powierzchnię [m^2]"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wtyczka_QGISDialogBase = QtWidgets.QDialog()
    ui = Ui_wtyczka_QGISDialogBase()
    ui.setupUi(wtyczka_QGISDialogBase)
    wtyczka_QGISDialogBase.show()
    sys.exit(app.exec_())
